// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bobobo80/go-oauth2-ent/ent/oauthtoken"
)

// OAuthTokenCreate is the builder for creating a OAuthToken entity.
type OAuthTokenCreate struct {
	config
	mutation *OAuthTokenMutation
	hooks    []Hook
}

// SetExpiredAt sets the "expired_at" field.
func (otc *OAuthTokenCreate) SetExpiredAt(t time.Time) *OAuthTokenCreate {
	otc.mutation.SetExpiredAt(t)
	return otc
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (otc *OAuthTokenCreate) SetNillableExpiredAt(t *time.Time) *OAuthTokenCreate {
	if t != nil {
		otc.SetExpiredAt(*t)
	}
	return otc
}

// SetCode sets the "code" field.
func (otc *OAuthTokenCreate) SetCode(s string) *OAuthTokenCreate {
	otc.mutation.SetCode(s)
	return otc
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (otc *OAuthTokenCreate) SetNillableCode(s *string) *OAuthTokenCreate {
	if s != nil {
		otc.SetCode(*s)
	}
	return otc
}

// SetAccess sets the "access" field.
func (otc *OAuthTokenCreate) SetAccess(s string) *OAuthTokenCreate {
	otc.mutation.SetAccess(s)
	return otc
}

// SetNillableAccess sets the "access" field if the given value is not nil.
func (otc *OAuthTokenCreate) SetNillableAccess(s *string) *OAuthTokenCreate {
	if s != nil {
		otc.SetAccess(*s)
	}
	return otc
}

// SetRefresh sets the "refresh" field.
func (otc *OAuthTokenCreate) SetRefresh(s string) *OAuthTokenCreate {
	otc.mutation.SetRefresh(s)
	return otc
}

// SetNillableRefresh sets the "refresh" field if the given value is not nil.
func (otc *OAuthTokenCreate) SetNillableRefresh(s *string) *OAuthTokenCreate {
	if s != nil {
		otc.SetRefresh(*s)
	}
	return otc
}

// SetData sets the "data" field.
func (otc *OAuthTokenCreate) SetData(s string) *OAuthTokenCreate {
	otc.mutation.SetData(s)
	return otc
}

// Mutation returns the OAuthTokenMutation object of the builder.
func (otc *OAuthTokenCreate) Mutation() *OAuthTokenMutation {
	return otc.mutation
}

// Save creates the OAuthToken in the database.
func (otc *OAuthTokenCreate) Save(ctx context.Context) (*OAuthToken, error) {
	otc.defaults()
	return withHooks[*OAuthToken, OAuthTokenMutation](ctx, otc.sqlSave, otc.mutation, otc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (otc *OAuthTokenCreate) SaveX(ctx context.Context) *OAuthToken {
	v, err := otc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (otc *OAuthTokenCreate) Exec(ctx context.Context) error {
	_, err := otc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (otc *OAuthTokenCreate) ExecX(ctx context.Context) {
	if err := otc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (otc *OAuthTokenCreate) defaults() {
	if _, ok := otc.mutation.ExpiredAt(); !ok {
		v := oauthtoken.DefaultExpiredAt()
		otc.mutation.SetExpiredAt(v)
	}
	if _, ok := otc.mutation.Code(); !ok {
		v := oauthtoken.DefaultCode
		otc.mutation.SetCode(v)
	}
	if _, ok := otc.mutation.Access(); !ok {
		v := oauthtoken.DefaultAccess
		otc.mutation.SetAccess(v)
	}
	if _, ok := otc.mutation.Refresh(); !ok {
		v := oauthtoken.DefaultRefresh
		otc.mutation.SetRefresh(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (otc *OAuthTokenCreate) check() error {
	if _, ok := otc.mutation.ExpiredAt(); !ok {
		return &ValidationError{Name: "expired_at", err: errors.New(`ent: missing required field "OAuthToken.expired_at"`)}
	}
	if _, ok := otc.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "OAuthToken.code"`)}
	}
	if v, ok := otc.mutation.Code(); ok {
		if err := oauthtoken.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "OAuthToken.code": %w`, err)}
		}
	}
	if _, ok := otc.mutation.Access(); !ok {
		return &ValidationError{Name: "access", err: errors.New(`ent: missing required field "OAuthToken.access"`)}
	}
	if v, ok := otc.mutation.Access(); ok {
		if err := oauthtoken.AccessValidator(v); err != nil {
			return &ValidationError{Name: "access", err: fmt.Errorf(`ent: validator failed for field "OAuthToken.access": %w`, err)}
		}
	}
	if _, ok := otc.mutation.Refresh(); !ok {
		return &ValidationError{Name: "refresh", err: errors.New(`ent: missing required field "OAuthToken.refresh"`)}
	}
	if v, ok := otc.mutation.Refresh(); ok {
		if err := oauthtoken.RefreshValidator(v); err != nil {
			return &ValidationError{Name: "refresh", err: fmt.Errorf(`ent: validator failed for field "OAuthToken.refresh": %w`, err)}
		}
	}
	if _, ok := otc.mutation.Data(); !ok {
		return &ValidationError{Name: "data", err: errors.New(`ent: missing required field "OAuthToken.data"`)}
	}
	if v, ok := otc.mutation.Data(); ok {
		if err := oauthtoken.DataValidator(v); err != nil {
			return &ValidationError{Name: "data", err: fmt.Errorf(`ent: validator failed for field "OAuthToken.data": %w`, err)}
		}
	}
	return nil
}

func (otc *OAuthTokenCreate) sqlSave(ctx context.Context) (*OAuthToken, error) {
	if err := otc.check(); err != nil {
		return nil, err
	}
	_node, _spec := otc.createSpec()
	if err := sqlgraph.CreateNode(ctx, otc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	otc.mutation.id = &_node.ID
	otc.mutation.done = true
	return _node, nil
}

func (otc *OAuthTokenCreate) createSpec() (*OAuthToken, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthToken{config: otc.config}
		_spec = sqlgraph.NewCreateSpec(oauthtoken.Table, sqlgraph.NewFieldSpec(oauthtoken.FieldID, field.TypeInt))
	)
	if value, ok := otc.mutation.ExpiredAt(); ok {
		_spec.SetField(oauthtoken.FieldExpiredAt, field.TypeTime, value)
		_node.ExpiredAt = value
	}
	if value, ok := otc.mutation.Code(); ok {
		_spec.SetField(oauthtoken.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := otc.mutation.Access(); ok {
		_spec.SetField(oauthtoken.FieldAccess, field.TypeString, value)
		_node.Access = value
	}
	if value, ok := otc.mutation.Refresh(); ok {
		_spec.SetField(oauthtoken.FieldRefresh, field.TypeString, value)
		_node.Refresh = value
	}
	if value, ok := otc.mutation.Data(); ok {
		_spec.SetField(oauthtoken.FieldData, field.TypeString, value)
		_node.Data = value
	}
	return _node, _spec
}

// OAuthTokenCreateBulk is the builder for creating many OAuthToken entities in bulk.
type OAuthTokenCreateBulk struct {
	config
	builders []*OAuthTokenCreate
}

// Save creates the OAuthToken entities in the database.
func (otcb *OAuthTokenCreateBulk) Save(ctx context.Context) ([]*OAuthToken, error) {
	specs := make([]*sqlgraph.CreateSpec, len(otcb.builders))
	nodes := make([]*OAuthToken, len(otcb.builders))
	mutators := make([]Mutator, len(otcb.builders))
	for i := range otcb.builders {
		func(i int, root context.Context) {
			builder := otcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, otcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, otcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, otcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (otcb *OAuthTokenCreateBulk) SaveX(ctx context.Context) []*OAuthToken {
	v, err := otcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (otcb *OAuthTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := otcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (otcb *OAuthTokenCreateBulk) ExecX(ctx context.Context) {
	if err := otcb.Exec(ctx); err != nil {
		panic(err)
	}
}
