// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/bobobo80/go-oauth2-ent/ent/oauthtoken"
	"github.com/bobobo80/go-oauth2-ent/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	oauthtokenFields := schema.OAuthToken{}.Fields()
	_ = oauthtokenFields
	// oauthtokenDescExpiredAt is the schema descriptor for expired_at field.
	oauthtokenDescExpiredAt := oauthtokenFields[0].Descriptor()
	// oauthtoken.DefaultExpiredAt holds the default value on creation for the expired_at field.
	oauthtoken.DefaultExpiredAt = oauthtokenDescExpiredAt.Default.(func() time.Time)
	// oauthtokenDescCode is the schema descriptor for code field.
	oauthtokenDescCode := oauthtokenFields[1].Descriptor()
	// oauthtoken.DefaultCode holds the default value on creation for the code field.
	oauthtoken.DefaultCode = oauthtokenDescCode.Default.(string)
	// oauthtoken.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	oauthtoken.CodeValidator = oauthtokenDescCode.Validators[0].(func(string) error)
	// oauthtokenDescAccess is the schema descriptor for access field.
	oauthtokenDescAccess := oauthtokenFields[2].Descriptor()
	// oauthtoken.DefaultAccess holds the default value on creation for the access field.
	oauthtoken.DefaultAccess = oauthtokenDescAccess.Default.(string)
	// oauthtoken.AccessValidator is a validator for the "access" field. It is called by the builders before save.
	oauthtoken.AccessValidator = oauthtokenDescAccess.Validators[0].(func(string) error)
	// oauthtokenDescRefresh is the schema descriptor for refresh field.
	oauthtokenDescRefresh := oauthtokenFields[3].Descriptor()
	// oauthtoken.DefaultRefresh holds the default value on creation for the refresh field.
	oauthtoken.DefaultRefresh = oauthtokenDescRefresh.Default.(string)
	// oauthtoken.RefreshValidator is a validator for the "refresh" field. It is called by the builders before save.
	oauthtoken.RefreshValidator = oauthtokenDescRefresh.Validators[0].(func(string) error)
	// oauthtokenDescData is the schema descriptor for data field.
	oauthtokenDescData := oauthtokenFields[4].Descriptor()
	// oauthtoken.DataValidator is a validator for the "data" field. It is called by the builders before save.
	oauthtoken.DataValidator = oauthtokenDescData.Validators[0].(func(string) error)
}
