// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// OAuthToken is the predicate function for oauthtoken builders.
type OAuthToken func(*sql.Selector)
